#ifndef FSM_H
#define FSM_H

// FSM state types
enum FSM_STATES 
	{ 
		FSM_STATE_NONE,
		FSM_FOLLOW_QUEEN,
		FSM_ATTACK_ENEMY,
		FSM_QUEEN_TARGETENEMY,
		FSM_QUEEN_SELECTSOLDIERS,
		FSM_ENEMY_WANDER,
		FSM_ENEMY_LOCUST_ATTACK
	};


#endif