BeeSiege: FSMBeeAIControl Class Reference
FSMBeeAIControl Class Reference
#include <FSMBeeAIControl.h>
Private Member Functions
FSMBeeAIControl (Bee *bee)
void Update (int t)
void UpdatePerceptions (int t)
void Init ()
Private Attributes
GameObj * m_nearestEnemy
GameObj * m_nearestPowerUp
float m_nearestEnemyDist
float m_nearestPowerUpDist
NiPoint3 m_collidePt
bool m_willCollide
bool m_powerUpNear
float m_safetyRadius
FSMBeeMachine * m_bee_machine
Bee * m_bee
Detailed Description
Definition at line 10 of file FSMBeeAIControl.h.
Constructor & Destructor Documentation
FSMBeeAIControl::FSMBeeAIControl (Bee * bee) [private]
Definition at line 7 of file FSMBeeAIControl.cpp.
References FSMBeeMachine::AddState(), FSM_MACH_BEE, m_bee, m_bee_machine, and FSMBeeMachine::SetDefaultState().
Member Function Documentation
void FSMBeeAIControl::Update (int t) [private, virtual]
Reimplemented from FSMAIControl.
Definition at line 19 of file FSMBeeAIControl.cpp.
References m_bee, m_bee_machine, FSMBeeMachine::Reset(), FSMBeeMachine::UpdateMachine(), and UpdatePerceptions().
void FSMBeeAIControl::UpdatePerceptions (int t) [private, virtual]
Reimplemented from FSMAIControl.
Definition at line 31 of file FSMBeeAIControl.cpp.
References m_nearestEnemy, m_nearestEnemyDist, m_nearestPowerUp, m_nearestPowerUpDist, m_powerUpNear, m_safetyRadius, m_willCollide, and POWERUP_SCAN_DIST.
Referenced by Update().
void FSMBeeAIControl::Init () [private, virtual]
Reimplemented from FSMAIControl.
Member Data Documentation
GameObj* FSMBeeAIControl::m_nearestEnemy [private]
Definition at line 14 of file FSMBeeAIControl.h.
Referenced by UpdatePerceptions().
GameObj* FSMBeeAIControl::m_nearestPowerUp [private]
Definition at line 15 of file FSMBeeAIControl.h.
Referenced by UpdatePerceptions().
float FSMBeeAIControl::m_nearestEnemyDist [private]
Definition at line 16 of file FSMBeeAIControl.h.
Referenced by UpdatePerceptions().
float FSMBeeAIControl::m_nearestPowerUpDist [private]
Definition at line 17 of file FSMBeeAIControl.h.
Referenced by UpdatePerceptions().
NiPoint3 FSMBeeAIControl::m_collidePt [private]
Definition at line 18 of file FSMBeeAIControl.h.
bool FSMBeeAIControl::m_willCollide [private]
Definition at line 19 of file FSMBeeAIControl.h.
Referenced by UpdatePerceptions().
bool FSMBeeAIControl::m_powerUpNear [private]
Definition at line 20 of file FSMBeeAIControl.h.
Referenced by UpdatePerceptions().
float FSMBeeAIControl::m_safetyRadius [private]
Definition at line 21 of file FSMBeeAIControl.h.
Referenced by UpdatePerceptions().
FSMBeeMachine* FSMBeeAIControl::m_bee_machine [private]
Definition at line 28 of file FSMBeeAIControl.h.
Referenced by FSMBeeAIControl(), and Update().
Bee* FSMBeeAIControl::m_bee [private]
Definition at line 29 of file FSMBeeAIControl.h.
Referenced by FSMBeeAIControl(), and Update().
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/FSMBeeAIControl.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/FSMBeeAIControl.cpp