BeeSiege: Queen Class Reference
Queen Class Reference
#include <Queen.h>
Public Member Functions
Queen ()
~Queen ()
void MoveForward ()
void MoveBack ()
void StrafeLeft ()
void StrafeRight ()
void Rotate (float dx, float dy)
void AddSoldier (BeePtr soldier)
void CycleTarget (const NiTPointerList< GameCharacterPtr > &enemies)
void SelectMoreSoldiers ()
void StopSelectingSoldiers ()
Private Member Functions
void DoExtraUpdates (float fTime)
bool DoExtraInits ()
BeePtr FindSoldierClosestTo (const NxVec3 &target)
Private Attributes
NiTPointerList< BeePtr > m_lSoldiers
NiTPointerList< BeePtr > m_lSelectedSoldiers
NiTListIterator m_itCurrentTargetPosition
GameCharacterPtr m_spCurrentTarget
const float m_fcQueenViewRadius
float m_fSelectionTimer
Detailed Description
Definition at line 26 of file Queen.h.
Constructor & Destructor Documentation
Queen::Queen ()
Queen: The queen bee that the player controlls Ctor
Definition at line 17 of file Queen.cpp.
Queen::~Queen ()
Dtor
Definition at line 30 of file Queen.cpp.
References m_lSelectedSoldiers, m_lSoldiers, and m_spCurrentTarget.
Member Function Documentation
void Queen::MoveForward ()
Adds a forward force
Definition at line 84 of file Queen.cpp.
References SingletonObj< ConfigurationManager >::Get(), and GameCharacter::m_spAgent.
void Queen::MoveBack ()
Adds a backward force
Definition at line 94 of file Queen.cpp.
References SingletonObj< ConfigurationManager >::Get(), and GameCharacter::m_spAgent.
void Queen::StrafeLeft ()
Adds a left force
Definition at line 104 of file Queen.cpp.
References SingletonObj< ConfigurationManager >::Get(), and GameCharacter::m_spAgent.
void Queen::StrafeRight ()
Adds a right force
Definition at line 115 of file Queen.cpp.
References SingletonObj< ConfigurationManager >::Get(), and GameCharacter::m_spAgent.
void Queen::Rotate (float dx, float dy)
Adds a torque
Parameters:
dx
dy
Definition at line 127 of file Queen.cpp.
References SingletonObj< ConfigurationManager >::Get(), GameCharacter::m_spAgent, ConfigurationManager::queen_moveUpSpeedGain, and ConfigurationManager::queen_rotationGain.
void Queen::AddSoldier (BeePtr soldier)
Adds a soldier bee to the Queen's soldier list
Parameters:
soldier
Definition at line 140 of file Queen.cpp.
References m_lSoldiers.
void Queen::CycleTarget (const NiTPointerList< GameCharacterPtr > & enemies)
Targets an enemy or cycles through targets if a target already exists
Parameters:
enemies
Definition at line 151 of file Queen.cpp.
References m_fcQueenViewRadius, m_itCurrentTargetPosition, GameCharacter::m_spAgent, and m_spCurrentTarget.
void Queen::SelectMoreSoldiers ()
Select more soldiers. Soldiers are selected according to their distance from the target
Definition at line 226 of file Queen.cpp.
References FindSoldierClosestTo(), SingletonObj< ConfigurationManager >::Get(), SingletonObj< GameManager >::Get(), GameManager::GetDeltaTime(), m_fSelectionTimer, m_lSelectedSoldiers, m_lSoldiers, and m_spCurrentTarget.
void Queen::StopSelectingSoldiers ()
Stop selecting soldiers and send them to attack the target
Definition at line 258 of file Queen.cpp.
References SingletonObj< ConfigurationManager >::Get(), m_fSelectionTimer, m_lSelectedSoldiers, m_lSoldiers, m_spCurrentTarget, and ConfigurationManager::timer_selectSoldiers.
void Queen::DoExtraUpdates (float fTime) [private, virtual]
Does extra updates
Parameters:
fTime
Implements GameCharacter.
Definition at line 42 of file Queen.cpp.
References m_fcQueenViewRadius, GameCharacter::m_spAgent, and m_spCurrentTarget.
bool Queen::DoExtraInits () [private, virtual]
Does extra initializations
Returns:
bool
Reimplemented from GameCharacter.
Definition at line 70 of file Queen.cpp.
References GameCharacter::DoExtraInits().
BeePtr Queen::FindSoldierClosestTo (const NxVec3 & target) [private]
Iterates through the list of bees and finds the bee closest to a target
Parameters:
target
Returns:
BeePtr
Definition at line 304 of file Queen.cpp.
References m_lSoldiers.
Referenced by SelectMoreSoldiers().
Member Data Documentation
NiTPointerList<BeePtr> Queen::m_lSoldiers [private]
Definition at line 55 of file Queen.h.
Referenced by AddSoldier(), FindSoldierClosestTo(), SelectMoreSoldiers(), StopSelectingSoldiers(), and ~Queen().
NiTPointerList<BeePtr> Queen::m_lSelectedSoldiers [private]
Definition at line 56 of file Queen.h.
Referenced by SelectMoreSoldiers(), StopSelectingSoldiers(), and ~Queen().
NiTListIterator Queen::m_itCurrentTargetPosition [private]
Definition at line 57 of file Queen.h.
Referenced by CycleTarget().
GameCharacterPtr Queen::m_spCurrentTarget [private]
Definition at line 58 of file Queen.h.
Referenced by CycleTarget(), DoExtraUpdates(), SelectMoreSoldiers(), StopSelectingSoldiers(), and ~Queen().
const float Queen::m_fcQueenViewRadius [private]
Definition at line 59 of file Queen.h.
Referenced by CycleTarget(), and DoExtraUpdates().
float Queen::m_fSelectionTimer [private]
Definition at line 60 of file Queen.h.
Referenced by SelectMoreSoldiers(), and StopSelectingSoldiers().
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/Queen.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/Queen.cpp