BeeSiege: TextManager Class Reference
TextManager Class Reference
#include <TextManager.h>
Public Types
enum StringType { STRING_SELECTEDSOLDIERS = 0 }
Public Member Functions
bool Init (NiRenderer *renderer)
void UpdateText (StringType type, const char *text)
void DisplayText ()
Private Member Functions
TextManager ()
~TextManager ()
bool AddString (const char *text, NiFontPtr font, unsigned int flags, unsigned int maxLength, const NiColorA &color, short x, short y, StringType type)
Private Attributes
friend SingletonObj< TextManager >
NiTMap< StringType, Ni2DStringPtr > m_tStrings
NiRenderer * m_pRenderer
Detailed Description
Definition at line 9 of file TextManager.h.
Member Enumeration Documentation
enum TextManager::StringType
Enumerator:
STRING_SELECTEDSOLDIERS
Definition at line 14 of file TextManager.h.
Constructor & Destructor Documentation
TextManager::TextManager () [private]
Displays text on screen. Singleton Class. Ctor
Definition at line 12 of file TextManager.cpp.
TextManager::~TextManager () [private]
Dtor
Definition at line 20 of file TextManager.cpp.
References m_tStrings.
Member Function Documentation
bool TextManager::Init (NiRenderer * renderer)
Initializes the manager
Parameters:
renderer
Returns:
bool
Definition at line 62 of file TextManager.cpp.
References AddString(), SingletonObj< ResourceManager >::Get(), ResourceManager::GetFont(), m_pRenderer, ResourceManager::RES_FONT_SELECTEDSOLDIERS, and STRING_SELECTEDSOLDIERS.
Referenced by GameApp::CreateScene().
void TextManager::UpdateText (StringType type, const char * text)
Updates the text of a string
Parameters:
type
text
Definition at line 82 of file TextManager.cpp.
References m_tStrings.
void TextManager::DisplayText ()
Renders text
Definition at line 93 of file TextManager.cpp.
References m_pRenderer, and m_tStrings.
Referenced by GameApp::RenderScreenItems().
bool TextManager::AddString (const char * text, NiFontPtr font, unsigned int flags, unsigned int maxLength, const NiColorA & color, short x, short y, StringType type) [private]
Adds a string to the list of strings to be displayed
Parameters:
text,: The text
font,: The font
flags,: String flags
maxLength,: Maximum text length
color,: Color of text
x,: x position
y,: y position:
type,: TOBEREMOVED
Returns:
bool
Definition at line 39 of file TextManager.cpp.
References m_tStrings.
Referenced by Init().
Member Data Documentation
friend TextManager::SingletonObj< TextManager > [private]
Definition at line 11 of file TextManager.h.
NiTMap<StringType, Ni2DStringPtr> TextManager::m_tStrings [private]
Definition at line 32 of file TextManager.h.
Referenced by AddString(), DisplayText(), UpdateText(), and ~TextManager().
NiRenderer* TextManager::m_pRenderer [private]
Definition at line 33 of file TextManager.h.
Referenced by DisplayText(), and Init().
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/TextManager.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/TextManager.cpp