BeeSiege: FSMEnemyAIControl Class Reference
FSMEnemyAIControl Class Reference
#include <FSMEnemyAIControl.h>
Public Member Functions
FSMEnemyAIControl (Locust *locust)
void Update (int t)
void UpdatePerceptions (int t)
void Init ()
Public Attributes
GameObj * m_nearestBee
float m_nearestBeeDist
float m_distFromQueen
NiPoint3 m_collidePt
bool m_willCollide
float m_safetyRadius
Private Attributes
FSMEnemyMachine * m_enemy_machine
Locust * m_enemy
Detailed Description
Definition at line 10 of file FSMEnemyAIControl.h.
Constructor & Destructor Documentation
FSMEnemyAIControl::FSMEnemyAIControl (Locust * locust)
Definition at line 6 of file FSMEnemyAIControl.cpp.
References FSMEnemyMachine::AddState(), FSM_MACH_ENEMY, m_enemy, m_enemy_machine, and FSMEnemyMachine::SetDefaultState().
Member Function Documentation
void FSMEnemyAIControl::Update (int t) [virtual]
Reimplemented from FSMAIControl.
Definition at line 17 of file FSMEnemyAIControl.cpp.
References m_enemy, m_enemy_machine, FSMEnemyMachine::Reset(), FSMEnemyMachine::UpdateMachine(), and UpdatePerceptions().
void FSMEnemyAIControl::UpdatePerceptions (int t) [virtual]
Reimplemented from FSMAIControl.
Definition at line 29 of file FSMEnemyAIControl.cpp.
References m_nearestBee, m_nearestBeeDist, m_safetyRadius, and m_willCollide.
Referenced by Update().
void FSMEnemyAIControl::Init () [virtual]
Reimplemented from FSMAIControl.
Member Data Documentation
GameObj* FSMEnemyAIControl::m_nearestBee
Definition at line 15 of file FSMEnemyAIControl.h.
Referenced by UpdatePerceptions().
float FSMEnemyAIControl::m_nearestBeeDist
Definition at line 16 of file FSMEnemyAIControl.h.
Referenced by UpdatePerceptions().
float FSMEnemyAIControl::m_distFromQueen
Definition at line 17 of file FSMEnemyAIControl.h.
NiPoint3 FSMEnemyAIControl::m_collidePt
Definition at line 18 of file FSMEnemyAIControl.h.
bool FSMEnemyAIControl::m_willCollide
Definition at line 19 of file FSMEnemyAIControl.h.
Referenced by UpdatePerceptions().
float FSMEnemyAIControl::m_safetyRadius
Definition at line 20 of file FSMEnemyAIControl.h.
Referenced by UpdatePerceptions().
FSMEnemyMachine* FSMEnemyAIControl::m_enemy_machine [private]
Definition at line 27 of file FSMEnemyAIControl.h.
Referenced by FSMEnemyAIControl(), and Update().
Locust* FSMEnemyAIControl::m_enemy [private]
Definition at line 28 of file FSMEnemyAIControl.h.
Referenced by FSMEnemyAIControl(), and Update().
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/FSMEnemyAIControl.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/FSMEnemyAIControl.cpp