BeeSiege: GameObj3d Class Reference
GameObj3d Class Reference
#include <GameObj3d.h>
Public Member Functions
GameObj3d (ResourceManager::ResourceType type)
virtual ~GameObj3d ()
NiNodePtr GetNode () const
NiPhysXPropPtr GetProp () const
void SetEmmitance (const NiColor &color)
Protected Member Functions
bool Init (NiNodePtr attachToThis)
bool Init (NiNodePtr attachToThis, NiPhysXScenePtr attachToScene)
void Update (float fTime)
Protected Attributes
ResourceManager::ResourceType m_Type
NiNodePtr m_spNode
NiPhysXPropPtr m_spProp
NiPoint3 m_Pos
NiMatrix3 m_Rot
Private Member Functions
virtual void DoExtraUpdates (float fTime)=0
virtual bool DoExtraInits ()=0
void SetEmmitanceForNode (NiAVObject *n, const NiColor &color)
Friends
class GameManager
Detailed Description
Definition at line 12 of file GameObj3d.h.
Constructor & Destructor Documentation
GameObj3d::GameObj3d (ResourceManager::ResourceType type)
A GameObj with 3d attributes Ctor
Parameters:
type
Definition at line 14 of file GameObj3d.cpp.
GameObj3d::~GameObj3d () [virtual]
Dtor
Definition at line 27 of file GameObj3d.cpp.
References m_spNode, and m_spProp.
Member Function Documentation
NiNodePtr GameObj3d::GetNode () const [inline]
Definition at line 19 of file GameObj3d.h.
References m_spNode.
NiPhysXPropPtr GameObj3d::GetProp () const [inline]
Definition at line 20 of file GameObj3d.h.
References m_spProp.
void GameObj3d::SetEmmitance (const NiColor & color)
Changes the object's emmisive color
Parameters:
color
Definition at line 106 of file GameObj3d.cpp.
References m_spNode, and SetEmmitanceForNode().
bool GameObj3d::Init (NiNodePtr attachToThis) [protected]
Initializes the 3d Object
Parameters:
attachToThis
Returns:
bool
Definition at line 40 of file GameObj3d.cpp.
References DoExtraInits(), SingletonObj< ResourceManager >::Get(), ResourceManager::GetNode(), m_spNode, and m_Type.
bool GameObj3d::Init (NiNodePtr attachToThis, NiPhysXScenePtr attachToScene) [protected]
Initializes the 3d Object with PhysX attributes
Parameters:
attachToThis
attachToScene
Returns:
bool
Definition at line 64 of file GameObj3d.cpp.
References DoExtraInits(), SingletonObj< ResourceManager >::Get(), ResourceManager::GetNodeProp(), m_spNode, m_spProp, and m_Type.
void GameObj3d::Update (float fTime) [protected]
Updates the object's attributes
Parameters:
fTime
Definition at line 90 of file GameObj3d.cpp.
References DoExtraUpdates(), and m_spNode.
virtual void GameObj3d::DoExtraUpdates (float fTime) [private, pure virtual]
Implemented in Bee, GameCharacter, Locust, and Queen.
Referenced by Update().
virtual bool GameObj3d::DoExtraInits () [private, pure virtual]
Implemented in Bee, GameCharacter, Locust, and Queen.
Referenced by Init().
void GameObj3d::SetEmmitanceForNode (NiAVObject * n, const NiColor & color) [private]
The recursive function that does all the work, in order to change the object's emmisive color
Parameters:
n
color
Definition at line 118 of file GameObj3d.cpp.
Referenced by SetEmmitance().
Friends And Related Function Documentation
friend class GameManager [friend]
Definition at line 14 of file GameObj3d.h.
Member Data Documentation
ResourceManager::ResourceType GameObj3d::m_Type [protected]
Definition at line 28 of file GameObj3d.h.
Referenced by Init().
NiNodePtr GameObj3d::m_spNode [protected]
Definition at line 29 of file GameObj3d.h.
Referenced by GetNode(), Init(), SetEmmitance(), Update(), and ~GameObj3d().
NiPhysXPropPtr GameObj3d::m_spProp [protected]
Definition at line 30 of file GameObj3d.h.
Referenced by GameCharacter::DoExtraInits(), GetProp(), Init(), and ~GameObj3d().
NiPoint3 GameObj3d::m_Pos [protected]
Definition at line 31 of file GameObj3d.h.
NiMatrix3 GameObj3d::m_Rot [protected]
Definition at line 32 of file GameObj3d.h.
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/GameObj3d.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/GameObj3d.cpp