BeeSiege: ConfigurationManager Class Reference
ConfigurationManager Class Reference
#include <ConfigurationManager.h>
Public Member Functions
bool ReadConfigurationFile (const char *file)
Public Attributes
float agent_maxForce
float agent_maxTorque
float agent_maxVelocity
float agent_maxAngVel
float characterController_springConstant
float characterController_damping
float cameraController_distanceFromTarget
float cameraController_maxVelocity
float cameraController_damping
float cameraController_springConstant
float arrival_constant
float alignment_constant
float alignment_radius
float cohesion_constant
float cohesion_radius
float departure_constant
float separation_constant
float separation_radius
float wander_constant
float wander_noise
float bee_distanceFromTarget
float queen_speedGain
float queen_rotationGain
float queen_moveUpSpeedGain
float queen_viewRadius
float timer_selectSoldiers
Private Member Functions
ConfigurationManager ()
~ConfigurationManager ()
bool ReadFloat (float &value, TiXmlElement *node, const char *child)
bool ReadControllers (TiXmlElement *node)
bool ReadAgents (TiXmlElement *node)
bool ReadCharacterController (TiXmlElement *node)
bool ReadCameraController (TiXmlElement *node)
bool ReadBehaviors (TiXmlElement *node)
bool ReadArrival (TiXmlElement *node)
bool ReadAlignment (TiXmlElement *node)
bool ReadCohesion (TiXmlElement *node)
bool ReadDeparture (TiXmlElement *node)
bool ReadSeparation (TiXmlElement *node)
bool ReadWander (TiXmlElement *node)
bool ReadCharacters (TiXmlElement *node)
bool ReadBee (TiXmlElement *node)
bool ReadQueen (TiXmlElement *node)
bool ReadTimers (TiXmlElement *node)
Private Attributes
friend SingletonObj< ConfigurationManager >
Detailed Description
Definition at line 8 of file ConfigurationManager.h.
Constructor & Destructor Documentation
ConfigurationManager::ConfigurationManager () [private]
Loads game constants from an XML file. Uses TinyXML for reading the XML file. Singleton class. Ctor
Definition at line 13 of file ConfigurationManager.cpp.
ConfigurationManager::~ConfigurationManager () [private]
Dtor
Definition at line 21 of file ConfigurationManager.cpp.
Member Function Documentation
bool ConfigurationManager::ReadConfigurationFile (const char * file)
Reads configuration file
Parameters:
file
Returns:
bool
Definition at line 32 of file ConfigurationManager.cpp.
References ReadBehaviors(), ReadCharacters(), ReadControllers(), and ReadTimers().
Referenced by GameManager::Init().
bool ConfigurationManager::ReadFloat (float & value, TiXmlElement * node, const char * child) [private]
Reads a flot value from an XML file
Parameters:
value
node
child
Returns:
bool
Definition at line 74 of file ConfigurationManager.cpp.
Referenced by ReadAgents(), ReadAlignment(), ReadArrival(), ReadBee(), ReadCameraController(), ReadCharacterController(), ReadCohesion(), ReadDeparture(), ReadQueen(), ReadSeparation(), ReadTimers(), and ReadWander().
bool ConfigurationManager::ReadControllers (TiXmlElement * node) [private]
Reads controllers
Parameters:
node
Returns:
bool
Definition at line 96 of file ConfigurationManager.cpp.
References ReadAgents(), ReadCameraController(), and ReadCharacterController().
Referenced by ReadConfigurationFile().
bool ConfigurationManager::ReadAgents (TiXmlElement * node) [private]
Reads agents
Parameters:
node
Returns:
bool
Definition at line 117 of file ConfigurationManager.cpp.
References agent_maxAngVel, agent_maxForce, agent_maxTorque, agent_maxVelocity, and ReadFloat().
Referenced by ReadControllers().
bool ConfigurationManager::ReadCharacterController (TiXmlElement * node) [private]
Reads a character controller
Parameters:
node
Returns:
bool
Definition at line 140 of file ConfigurationManager.cpp.
References characterController_damping, characterController_springConstant, and ReadFloat().
Referenced by ReadControllers().
bool ConfigurationManager::ReadCameraController (TiXmlElement * node) [private]
Reads a camera controller
Parameters:
node
Returns:
bool
Definition at line 162 of file ConfigurationManager.cpp.
References cameraController_damping, cameraController_distanceFromTarget, cameraController_maxVelocity, cameraController_springConstant, and ReadFloat().
Referenced by ReadControllers().
bool ConfigurationManager::ReadBehaviors (TiXmlElement * node) [private]
Reads behaviors
Parameters:
node
Returns:
bool
Definition at line 187 of file ConfigurationManager.cpp.
References ReadAlignment(), ReadArrival(), ReadCohesion(), ReadDeparture(), ReadSeparation(), and ReadWander().
Referenced by ReadConfigurationFile().
bool ConfigurationManager::ReadArrival (TiXmlElement * node) [private]
Reads Arrival
Parameters:
node
Returns:
bool
Definition at line 219 of file ConfigurationManager.cpp.
References arrival_constant, and ReadFloat().
Referenced by ReadBehaviors().
bool ConfigurationManager::ReadAlignment (TiXmlElement * node) [private]
Reads Alignment
Parameters:
node
Returns:
bool
Definition at line 238 of file ConfigurationManager.cpp.
References alignment_constant, alignment_radius, and ReadFloat().
Referenced by ReadBehaviors().
bool ConfigurationManager::ReadCohesion (TiXmlElement * node) [private]
Reads Cohesion
Parameters:
node
Returns:
bool
Definition at line 258 of file ConfigurationManager.cpp.
References cohesion_constant, cohesion_radius, and ReadFloat().
Referenced by ReadBehaviors().
bool ConfigurationManager::ReadDeparture (TiXmlElement * node) [private]
Reads Departure
Parameters:
node
Returns:
bool
Definition at line 278 of file ConfigurationManager.cpp.
References departure_constant, and ReadFloat().
Referenced by ReadBehaviors().
bool ConfigurationManager::ReadSeparation (TiXmlElement * node) [private]
Reads Separation
Parameters:
node
Returns:
bool
Definition at line 297 of file ConfigurationManager.cpp.
References ReadFloat(), separation_constant, and separation_radius.
Referenced by ReadBehaviors().
bool ConfigurationManager::ReadWander (TiXmlElement * node) [private]
Reads Wander
Parameters:
node
Returns:
bool
Definition at line 317 of file ConfigurationManager.cpp.
References ReadFloat(), wander_constant, and wander_noise.
Referenced by ReadBehaviors().
bool ConfigurationManager::ReadCharacters (TiXmlElement * node) [private]
Reads Characters
Parameters:
node
Returns:
bool
Definition at line 337 of file ConfigurationManager.cpp.
References ReadBee(), and ReadQueen().
Referenced by ReadConfigurationFile().
bool ConfigurationManager::ReadBee (TiXmlElement * node) [private]
Reads Bees
Parameters:
node
Returns:
bool
Definition at line 357 of file ConfigurationManager.cpp.
References bee_distanceFromTarget, and ReadFloat().
Referenced by ReadCharacters().
bool ConfigurationManager::ReadQueen (TiXmlElement * node) [private]
Reads Queen
Parameters:
node
Returns:
bool
Definition at line 376 of file ConfigurationManager.cpp.
References queen_moveUpSpeedGain, queen_rotationGain, queen_speedGain, queen_viewRadius, and ReadFloat().
Referenced by ReadCharacters().
bool ConfigurationManager::ReadTimers (TiXmlElement * node) [private]
Reads timers
Parameters:
node
Returns:
bool
Definition at line 398 of file ConfigurationManager.cpp.
References ReadFloat(), and timer_selectSoldiers.
Referenced by ReadConfigurationFile().
Member Data Documentation
friend ConfigurationManager::SingletonObj< ConfigurationManager > [private]
Definition at line 10 of file ConfigurationManager.h.
float ConfigurationManager::agent_maxForce
Definition at line 15 of file ConfigurationManager.h.
Referenced by ReadAgents().
float ConfigurationManager::agent_maxTorque
Definition at line 16 of file ConfigurationManager.h.
Referenced by ReadAgents().
float ConfigurationManager::agent_maxVelocity
Definition at line 17 of file ConfigurationManager.h.
Referenced by ReadAgents().
float ConfigurationManager::agent_maxAngVel
Definition at line 18 of file ConfigurationManager.h.
Referenced by ReadAgents().
float ConfigurationManager::characterController_springConstant
Definition at line 19 of file ConfigurationManager.h.
Referenced by ReadCharacterController().
float ConfigurationManager::characterController_damping
Definition at line 20 of file ConfigurationManager.h.
Referenced by ReadCharacterController().
float ConfigurationManager::cameraController_distanceFromTarget
Definition at line 21 of file ConfigurationManager.h.
Referenced by ReadCameraController().
float ConfigurationManager::cameraController_maxVelocity
Definition at line 22 of file ConfigurationManager.h.
Referenced by ReadCameraController().
float ConfigurationManager::cameraController_damping
Definition at line 23 of file ConfigurationManager.h.
Referenced by ReadCameraController().
float ConfigurationManager::cameraController_springConstant
Definition at line 24 of file ConfigurationManager.h.
Referenced by ReadCameraController().
float ConfigurationManager::arrival_constant
Definition at line 25 of file ConfigurationManager.h.
Referenced by ReadArrival().
float ConfigurationManager::alignment_constant
Definition at line 26 of file ConfigurationManager.h.
Referenced by ReadAlignment().
float ConfigurationManager::alignment_radius
Definition at line 27 of file ConfigurationManager.h.
Referenced by ReadAlignment().
float ConfigurationManager::cohesion_constant
Definition at line 28 of file ConfigurationManager.h.
Referenced by ReadCohesion().
float ConfigurationManager::cohesion_radius
Definition at line 29 of file ConfigurationManager.h.
Referenced by ReadCohesion().
float ConfigurationManager::departure_constant
Definition at line 30 of file ConfigurationManager.h.
Referenced by ReadDeparture().
float ConfigurationManager::separation_constant
Definition at line 31 of file ConfigurationManager.h.
Referenced by ReadSeparation().
float ConfigurationManager::separation_radius
Definition at line 32 of file ConfigurationManager.h.
Referenced by ReadSeparation().
float ConfigurationManager::wander_constant
Definition at line 33 of file ConfigurationManager.h.
Referenced by ReadWander().
float ConfigurationManager::wander_noise
Definition at line 34 of file ConfigurationManager.h.
Referenced by ReadWander().
float ConfigurationManager::bee_distanceFromTarget
Definition at line 35 of file ConfigurationManager.h.
Referenced by ReadBee().
float ConfigurationManager::queen_speedGain
Definition at line 36 of file ConfigurationManager.h.
Referenced by ReadQueen().
float ConfigurationManager::queen_rotationGain
Definition at line 37 of file ConfigurationManager.h.
Referenced by ReadQueen(), and Queen::Rotate().
float ConfigurationManager::queen_moveUpSpeedGain
Definition at line 38 of file ConfigurationManager.h.
Referenced by ReadQueen(), and Queen::Rotate().
float ConfigurationManager::queen_viewRadius
Definition at line 39 of file ConfigurationManager.h.
Referenced by ReadQueen().
float ConfigurationManager::timer_selectSoldiers
Definition at line 40 of file ConfigurationManager.h.
Referenced by ReadTimers(), and Queen::StopSelectingSoldiers().
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/ConfigurationManager.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/ConfigurationManager.cpp