BeeSiege: CharacterController Class Reference
CharacterController Class Reference
#include <CharacterController.h>
Public Member Functions
CharacterController (Agent *agent)
virtual ~CharacterController ()
void Update (const NxVec3 &target)
void SetBehavior (BehaviorPtr b)
void ToggleSpringDynamics (bool off)
AgentInfoPtr GetAgentInfo () const
Protected Member Functions
void Sense (const NxVec3 &target)
void UpdateForces ()
void UpdatePhysX ()
void Clamp (float &degree, float minV, float maxV)
void Truncate (float &value, float minV, float maxV)
float AngleDiff (float source, float target)
Protected Attributes
Agent * m_pAgent
AgentInfoPtr m_spAgentInfo
BehaviorPtr m_spBehavior
const float m_fcKv0
const float m_fcDamp
const float m_fcPI
bool m_bTurnSpringsOff
Detailed Description
Definition at line 12 of file CharacterController.h.
Constructor & Destructor Documentation
CharacterController::CharacterController (Agent * agent)
Ctor
Parameters:
agent
Definition at line 26 of file CharacterController.cpp.
CharacterController::~CharacterController () [virtual]
Dtor
Definition at line 44 of file CharacterController.cpp.
References m_spAgentInfo, and m_spBehavior.
Member Function Documentation
void CharacterController::Update (const NxVec3 & target)
Senses the environment to get a desired velocity, generates a force and updates the object's PhysX actor
Parameters:
target
Definition at line 56 of file CharacterController.cpp.
References Sense(), UpdateForces(), and UpdatePhysX().
void CharacterController::SetBehavior (BehaviorPtr b) [inline]
Definition at line 20 of file CharacterController.h.
References m_spBehavior.
void CharacterController::ToggleSpringDynamics (bool off) [inline]
Definition at line 21 of file CharacterController.h.
References m_bTurnSpringsOff.
AgentInfoPtr CharacterController::GetAgentInfo () const [inline]
Definition at line 22 of file CharacterController.h.
References m_spAgentInfo.
void CharacterController::Sense (const NxVec3 & target) [protected]
Executes the current behavior to get a desired velocity
Parameters:
target
Definition at line 68 of file CharacterController.cpp.
References Agent::GetActor(), m_pAgent, m_spAgentInfo, and m_spBehavior.
Referenced by Update().
void CharacterController::UpdateForces () [protected]
Generates a force based on a current and a desired velocity
Definition at line 84 of file CharacterController.cpp.
References m_fcDamp, m_fcKv0, and m_spAgentInfo.
Referenced by Update().
void CharacterController::UpdatePhysX () [protected]
Adds the force to the object's PhysX actor
Definition at line 106 of file CharacterController.cpp.
References Agent::GetActor(), m_bTurnSpringsOff, m_pAgent, and m_spAgentInfo.
Referenced by Update().
void CharacterController::Clamp (float & degree, float minV, float maxV) [inline, protected]
Definition at line 46 of file CharacterController.h.
void CharacterController::Truncate (float & value, float minV, float maxV) [inline, protected]
Definition at line 61 of file CharacterController.h.
float CharacterController::AngleDiff (float source, float target) [inline, protected]
Definition at line 69 of file CharacterController.h.
References m_fcPI.
Member Data Documentation
Agent* CharacterController::m_pAgent [protected]
Definition at line 31 of file CharacterController.h.
Referenced by Sense(), and UpdatePhysX().
AgentInfoPtr CharacterController::m_spAgentInfo [protected]
Definition at line 33 of file CharacterController.h.
Referenced by GetAgentInfo(), Sense(), UpdateForces(), UpdatePhysX(), and ~CharacterController().
BehaviorPtr CharacterController::m_spBehavior [protected]
Definition at line 35 of file CharacterController.h.
Referenced by Sense(), SetBehavior(), and ~CharacterController().
const float CharacterController::m_fcKv0 [protected]
Definition at line 37 of file CharacterController.h.
Referenced by UpdateForces().
const float CharacterController::m_fcDamp [protected]
Definition at line 39 of file CharacterController.h.
Referenced by UpdateForces().
const float CharacterController::m_fcPI [protected]
Definition at line 41 of file CharacterController.h.
Referenced by AngleDiff().
bool CharacterController::m_bTurnSpringsOff [protected]
Definition at line 43 of file CharacterController.h.
Referenced by ToggleSpringDynamics(), and UpdatePhysX().
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/CharacterController.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/CharacterController.cpp