BeeSiege: GameApp Class Reference
GameApp Class Reference
#include <GameApp.h>
Public Member Functions
GameApp ()
bool Initialize ()
bool CreateScene ()
void ProcessInput ()
void UpdateFrame ()
void RenderScreenItems ()
void Terminate ()
NiNodePtr GetScene () const
NiPhysXScenePtr GetPhysXScene () const
NiCameraPtr GetCamera () const
CameraControllerPtr GetCameraController () const
Protected Member Functions
void SetPhysXSDKParams (const NxParameter kParam=NX_PARAMS_NUM_VALUES)
bool CreatePhysXScene ()
Protected Attributes
NiPhysXManager * m_pPhysXManager
NiPhysXScenePtr m_spPhysXScene
CameraControllerPtr m_spCameraController
float m_fLastSimTime
Detailed Description
Definition at line 8 of file GameApp.h.
Constructor & Destructor Documentation
GameApp::GameApp ()
The constructor
Definition at line 33 of file GameApp.cpp.
Member Function Documentation
bool GameApp::Initialize ()
Initializes NiApplication
Returns:
bool
Definition at line 45 of file GameApp.cpp.
References m_pPhysXManager, and SetPhysXSDKParams().
bool GameApp::CreateScene ()
Creates the NiApplication's scene
Returns:
bool
Definition at line 62 of file GameApp.cpp.
References CreatePhysXScene(), SingletonObj< TextManager >::Get(), SingletonObj< GameManager >::Get(), SingletonObj< ResourceManager >::Get(), TextManager::Init(), GameManager::Init(), ResourceManager::Init(), m_fLastSimTime, m_spCameraController, and m_spPhysXScene.
void GameApp::ProcessInput ()
Processes user input
Definition at line 139 of file GameApp.cpp.
References SingletonObj< InputManager >::Get(), and InputManager::ProcessInput().
void GameApp::UpdateFrame ()
Updates the current frame
Definition at line 154 of file GameApp.cpp.
References SingletonObj< SoundManager >::Get(), SingletonObj< GameManager >::Get(), GameManager::GetQueen(), m_fLastSimTime, m_spCameraController, m_spPhysXScene, SoundManager::Update(), and GameManager::UpdateAll().
void GameApp::RenderScreenItems ()
Renders HUD
Definition at line 193 of file GameApp.cpp.
References TextManager::DisplayText(), and SingletonObj< TextManager >::Get().
void GameApp::Terminate ()
Frees memory
Definition at line 203 of file GameApp.cpp.
References SingletonObj< InputManager >::Destroy(), SingletonObj< ResourceManager >::Destroy(), SingletonObj< GameManager >::Destroy(), SingletonObj< TextManager >::Destroy(), m_pPhysXManager, m_spCameraController, and m_spPhysXScene.
NiNodePtr GameApp::GetScene () const [inline]
Definition at line 20 of file GameApp.h.
Referenced by InputManager::ProcessKeyboard().
NiPhysXScenePtr GameApp::GetPhysXScene () const [inline]
Definition at line 21 of file GameApp.h.
References m_spPhysXScene.
Referenced by InputManager::ProcessKeyboard().
NiCameraPtr GameApp::GetCamera () const [inline]
Definition at line 22 of file GameApp.h.
CameraControllerPtr GameApp::GetCameraController () const [inline]
Definition at line 23 of file GameApp.h.
References m_spCameraController.
Referenced by InputManager::ProcessMouse().
void GameApp::SetPhysXSDKParams (const NxParameter kParam = NX_PARAMS_NUM_VALUES) [protected]
Sets the default PhysX parameters
Parameters:
kParam
Definition at line 221 of file GameApp.cpp.
References m_pPhysXManager.
Referenced by Initialize().
bool GameApp::CreatePhysXScene () [protected]
Creates the main PhysX scene
Returns:
bool
Definition at line 254 of file GameApp.cpp.
References m_pPhysXManager, and m_spPhysXScene.
Referenced by CreateScene().
Member Data Documentation
NiPhysXManager* GameApp::m_pPhysXManager [protected]
Definition at line 32 of file GameApp.h.
Referenced by CreatePhysXScene(), Initialize(), SetPhysXSDKParams(), and Terminate().
NiPhysXScenePtr GameApp::m_spPhysXScene [protected]
Definition at line 33 of file GameApp.h.
Referenced by CreatePhysXScene(), CreateScene(), GetPhysXScene(), Terminate(), and UpdateFrame().
CameraControllerPtr GameApp::m_spCameraController [protected]
Definition at line 34 of file GameApp.h.
Referenced by CreateScene(), GetCameraController(), Terminate(), and UpdateFrame().
float GameApp::m_fLastSimTime [protected]
Definition at line 35 of file GameApp.h.
Referenced by CreateScene(), and UpdateFrame().
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/GameApp.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/GameApp.cpp