BeeSiege: ResourceManager Class Reference
ResourceManager Class Reference
#include <ResourceManager.h>
Public Types
enum ResourceType {
RES_MODEL_BEE, RES_MODEL_QUEEN, RES_MODEL_LOCUST, RES_MODEL_ENEMY2,
RES_MODEL_YELLOWBOX, RES_FONT_SELECTEDSOLDIERS, RES_SOUND_BEE
}
Public Member Functions
bool Init (NiStream *stream, NiRenderer *renderer)
NiNodePropPtr GetNodeProp (ResourceType type)
NiNodePtr GetNode (ResourceType type)
NiFontPtr GetFont (ResourceType type)
SoundPtr GetSound (ResourceType type)
Private Member Functions
ResourceManager ()
~ResourceManager ()
bool LoadNif (NiStream *stream, const std::string &filename, ResourceType type)
bool LoadFont (const std::string &filename, NiRenderer *renderer, ResourceType type)
bool LoadSound (const std::string &filename, ResourceType type)
Private Attributes
friend SingletonObj< ResourceManager >
NiTMap< ResourceType,
NiNodePropPtr > m_tResourcesModels
NiTMap< ResourceType, NiFontPtr > m_tResourcesFonts
NiTMap< ResourceType,
SoundDescPtr > m_tResourcesSounds
Detailed Description
Definition at line 15 of file ResourceManager.h.
Member Enumeration Documentation
enum ResourceManager::ResourceType
Enumerator:
RES_MODEL_BEE
RES_MODEL_QUEEN
RES_MODEL_LOCUST
RES_MODEL_ENEMY2
RES_MODEL_YELLOWBOX
RES_FONT_SELECTEDSOLDIERS
RES_SOUND_BEE
Definition at line 20 of file ResourceManager.h.
Constructor & Destructor Documentation
ResourceManager::ResourceManager () [private]
Ctor
Definition at line 20 of file ResourceManager.cpp.
ResourceManager::~ResourceManager () [private]
Dtor
Definition at line 28 of file ResourceManager.cpp.
References m_tResourcesFonts, m_tResourcesModels, and m_tResourcesSounds.
Member Function Documentation
bool ResourceManager::Init (NiStream * stream, NiRenderer * renderer)
Initializes the manager
Parameters:
stream
renderer
Returns:
bool
Definition at line 44 of file ResourceManager.cpp.
References LoadFont(), LoadNif(), RES_FONT_SELECTEDSOLDIERS, RES_MODEL_BEE, RES_MODEL_LOCUST, and RES_MODEL_QUEEN.
Referenced by GameApp::CreateScene().
NiNodePropPtr ResourceManager::GetNodeProp (ResourceType type)
Gets a node and a PhysX prop
Parameters:
type
Returns:
NiNodePropPtr
Definition at line 80 of file ResourceManager.cpp.
References m_tResourcesModels.
Referenced by GameObj3d::Init().
NiNodePtr ResourceManager::GetNode (ResourceType type)
Gets a node with no PhysX props
Parameters:
type
Returns:
NiNodePtr
Definition at line 103 of file ResourceManager.cpp.
References m_tResourcesModels.
Referenced by GameObj3d::Init().
NiFontPtr ResourceManager::GetFont (ResourceType type)
Gets a font
Parameters:
type
Returns:
NiFontPtr
Definition at line 121 of file ResourceManager.cpp.
References m_tResourcesFonts.
Referenced by TextManager::Init().
SoundPtr ResourceManager::GetSound (ResourceType type)
Gets a sound
Parameters:
type
Returns:
SoundPtr
Definition at line 139 of file ResourceManager.cpp.
References SoundManager::CreateSound(), SingletonObj< SoundManager >::Get(), and m_tResourcesSounds.
bool ResourceManager::LoadNif (NiStream * stream, const std::string & filename, ResourceType type) [private]
Referenced by Init().
bool ResourceManager::LoadFont (const std::string & filename, NiRenderer * renderer, ResourceType type) [private]
Loads a font
Parameters:
filename
renderer
type
Returns:
bool
Definition at line 212 of file ResourceManager.cpp.
References m_tResourcesFonts.
Referenced by Init().
bool ResourceManager::LoadSound (const std::string & filename, ResourceType type) [private]
Loads a sound
Parameters:
filename
type
Returns:
bool
Definition at line 240 of file ResourceManager.cpp.
References m_tResourcesSounds.
Member Data Documentation
friend ResourceManager::SingletonObj< ResourceManager > [private]
Definition at line 17 of file ResourceManager.h.
NiTMap<ResourceType , NiNodePropPtr> ResourceManager::m_tResourcesModels [private]
Definition at line 52 of file ResourceManager.h.
Referenced by GetNode(), GetNodeProp(), and ~ResourceManager().
NiTMap<ResourceType , NiFontPtr> ResourceManager::m_tResourcesFonts [private]
Definition at line 53 of file ResourceManager.h.
Referenced by GetFont(), LoadFont(), and ~ResourceManager().
NiTMap<ResourceType, SoundDescPtr> ResourceManager::m_tResourcesSounds [private]
Definition at line 54 of file ResourceManager.h.
Referenced by GetSound(), LoadSound(), and ~ResourceManager().
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/ResourceManager.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/ResourceManager.cpp