BeeSiege: InputManager Class Reference
InputManager Class Reference
#include <InputManager.h>
Public Member Functions
void ProcessInput (NiInputSystemPtr inputSystem, GameApp *gameApp)
Private Member Functions
InputManager ()
~InputManager ()
void ProcessKeyboard (NiInputKeyboard *keyboard, GameApp *gameApp)
void ProcessMouse (NiInputMouse *mouse, GameApp *gameApp)
Private Attributes
friend SingletonObj< InputManager >
Detailed Description
Definition at line 9 of file InputManager.h.
Constructor & Destructor Documentation
InputManager::InputManager () [private]
Handles user input. Singleton class. Ctor
Definition at line 15 of file InputManager.cpp.
InputManager::~InputManager () [private]
Dtor
Definition at line 23 of file InputManager.cpp.
Member Function Documentation
void InputManager::ProcessInput (NiInputSystemPtr inputSystem, GameApp * gameApp)
Processes keyboard and mouse input
Parameters:
inputSystem
gameApp
Definition at line 33 of file InputManager.cpp.
References ProcessKeyboard(), and ProcessMouse().
Referenced by GameApp::ProcessInput().
void InputManager::ProcessKeyboard (NiInputKeyboard * keyboard, GameApp * gameApp) [private]
Processes keyboard
Parameters:
keyboard
gameApp
Definition at line 45 of file InputManager.cpp.
References GameManager::AddObject(), SingletonObj< GameManager >::Get(), GameManager::GetEnemies(), GameApp::GetPhysXScene(), GameManager::GetQueen(), and GameApp::GetScene().
Referenced by ProcessInput().
void InputManager::ProcessMouse (NiInputMouse * mouse, GameApp * gameApp) [private]
Processes mouse
Parameters:
mouse
gameApp
Definition at line 97 of file InputManager.cpp.
References SingletonObj< GameManager >::Get(), GameApp::GetCameraController(), and GameManager::GetQueen().
Referenced by ProcessInput().
Member Data Documentation
friend InputManager::SingletonObj< InputManager > [private]
Definition at line 11 of file InputManager.h.
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/InputManager.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/InputManager.cpp