BeeSiege: FSMBeeMachine Class Reference
FSMBeeMachine Class Reference
#include <FSMBeeMachine.h>
Public Member Functions
FSMBeeMachine (int type=FSM_MACH_BEE)
void UpdateMachine (int i)
void AddState (FSMState *state)
void SetDefaultState (FSMState *state)
void SetGoalID (int goal)
bool TransitionState (int goal)
void Reset ()
Detailed Description
Definition at line 8 of file FSMBeeMachine.h.
Constructor & Destructor Documentation
FSMBeeMachine::FSMBeeMachine (int type = FSM_MACH_BEE) [inline]
Definition at line 11 of file FSMBeeMachine.h.
References FSMMachine::m_type.
Member Function Documentation
void FSMBeeMachine::UpdateMachine (int i) [virtual]
Reimplemented from FSMMachine.
Referenced by FSMBeeAIControl::Update().
void FSMBeeMachine::AddState (FSMState * state) [virtual]
Reimplemented from FSMMachine.
Referenced by FSMBeeAIControl::FSMBeeAIControl().
void FSMBeeMachine::SetDefaultState (FSMState * state) [inline, virtual]
Reimplemented from FSMMachine.
Definition at line 18 of file FSMBeeMachine.h.
References FSMMachine::m_defaultState.
Referenced by FSMBeeAIControl::FSMBeeAIControl().
void FSMBeeMachine::SetGoalID (int goal) [inline, virtual]
Reimplemented from FSMMachine.
Definition at line 22 of file FSMBeeMachine.h.
References FSMMachine::m_goalId.
bool FSMBeeMachine::TransitionState (int goal) [virtual]
Reimplemented from FSMMachine.
void FSMBeeMachine::Reset () [virtual]
Reimplemented from FSMMachine.
Referenced by FSMBeeAIControl::Update().
The documentation for this class was generated from the following file:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/FSMBeeMachine.h