BeeSiege: FSMQueenMachine Class Reference
FSMQueenMachine Class Reference
#include <FSMQueenMachine.h>
Public Member Functions
FSMQueenMachine (int type=FSM_MACH_QUEEN)
void UpdateMachine (int i)
void AddState (FSMState *state)
void SetDefaultState (FSMState *state)
void SetGoalID (int goal)
bool TransitionState (int goal)
void Reset ()
Detailed Description
Definition at line 7 of file FSMQueenMachine.h.
Constructor & Destructor Documentation
FSMQueenMachine::FSMQueenMachine (int type = FSM_MACH_QUEEN) [inline]
Definition at line 10 of file FSMQueenMachine.h.
References FSMMachine::m_type.
Member Function Documentation
void FSMQueenMachine::UpdateMachine (int i) [virtual]
Reimplemented from FSMMachine.
Referenced by FSMQueenAIControl::Update().
void FSMQueenMachine::AddState (FSMState * state) [virtual]
Reimplemented from FSMMachine.
Referenced by FSMQueenAIControl::FSMQueenAIControl().
void FSMQueenMachine::SetDefaultState (FSMState * state) [inline, virtual]
Reimplemented from FSMMachine.
Definition at line 17 of file FSMQueenMachine.h.
References FSMMachine::m_defaultState.
Referenced by FSMQueenAIControl::FSMQueenAIControl().
void FSMQueenMachine::SetGoalID (int goal) [inline, virtual]
Reimplemented from FSMMachine.
Definition at line 21 of file FSMQueenMachine.h.
References FSMMachine::m_goalId.
bool FSMQueenMachine::TransitionState (int goal) [virtual]
Reimplemented from FSMMachine.
void FSMQueenMachine::Reset () [virtual]
Reimplemented from FSMMachine.
Referenced by FSMQueenAIControl::Update().
The documentation for this class was generated from the following file:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/FSMQueenMachine.h