BeeSiege: Bee Class Reference
Bee Class Reference
#include <Bee.h>
Public Member Functions
Bee ()
~Bee ()
Private Member Functions
void DoExtraUpdates (float fTime)
bool DoExtraInits ()
Private Attributes
SoundPtr m_spSound
Detailed Description
Definition at line 7 of file Bee.h.
Constructor & Destructor Documentation
Bee::Bee ()
A Bee or a queen's soldier. Ctor
Definition at line 26 of file Bee.cpp.
Bee::~Bee ()
Dtor
Definition at line 34 of file Bee.cpp.
References m_spSound.
Member Function Documentation
void Bee::DoExtraUpdates (float fTime) [private, virtual]
Update the target the bee's controller
Parameters:
fTime
Implements GameCharacter.
Definition at line 44 of file Bee.cpp.
References SingletonObj< GameManager >::Get(), GameCharacter::GetAgent(), GameCharacter::m_pTarget, and GameCharacter::m_spAgent.
bool Bee::DoExtraInits () [private, virtual]
Create a behavior for the bee's controller and initialize the bee's properties
Returns:
bool
Reimplemented from GameCharacter.
Definition at line 73 of file Bee.cpp.
References GameManager::AddAgent(), GameCharacter::DoExtraInits(), SingletonObj< GameManager >::Get(), GameManager::GetQueen(), GameCharacter::m_pTarget, and GameCharacter::m_spAgent.
Member Data Documentation
SoundPtr Bee::m_spSound [private]
Definition at line 17 of file Bee.h.
Referenced by ~Bee().
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/Bee.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/Bee.cpp