BeeSiege: GameManager Class Reference
GameManager Class Reference
#include <GameManager.h>
Public Member Functions
bool Init (NiNodePtr parent, NiPhysXScenePtr physXScene, NiApplication *app)
void UpdateAll (float fTime)
bool AddObject (GameObj3dPtr object, NiNodePtr parent)
bool AddObject (GameObj3dPtr object, NiNodePtr parent, NiPhysXScenePtr physXScene)
void AddAgent (AgentPtr agent)
void AddEnemy (GameCharacterPtr enemy)
void RemoveEnemy (GameCharacterPtr enemy)
void RemoveObject (GameObj3dPtr object)
QueenPtr GetQueen () const
const NiTPointerList< AgentPtr > & GetAgents () const
GameApp * GetGameApp () const
const NiTPointerList
< GameCharacterPtr > & GetEnemies () const
const float GetDeltaTime () const
Private Member Functions
GameManager ()
~GameManager ()
Private Attributes
friend SingletonObj< GameManager >
NiTPointerList< GameObj3dPtr > m_lObjects
NiTPointerList< AgentPtr > m_lAgents
NiTPointerList< GameCharacterPtr > m_lEnemies
QueenPtr m_spQueen
GameApp * m_pGameApplication
float m_fDeltaTime
Detailed Description
Definition at line 28 of file GameManager.h.
Constructor & Destructor Documentation
GameManager::GameManager () [private]
Holds game objects and updates them. Singleton class. Ctor
Definition at line 18 of file GameManager.cpp.
GameManager::~GameManager () [private]
Dtor
Definition at line 26 of file GameManager.cpp.
References SingletonObj< ConfigurationManager >::Destroy(), m_lAgents, m_lEnemies, m_lObjects, and m_spQueen.
Member Function Documentation
bool GameManager::Init (NiNodePtr parent, NiPhysXScenePtr physXScene, NiApplication * app)
Initializes manager
Parameters:
parent
physXScene
app
Returns:
bool
return false;
Definition at line 45 of file GameManager.cpp.
References AddObject(), SingletonObj< ConfigurationManager >::Get(), m_pGameApplication, m_spQueen, and ConfigurationManager::ReadConfigurationFile().
Referenced by GameApp::CreateScene().
void GameManager::UpdateAll (float fTime)
Updates all game objects
Parameters:
fTime
Definition at line 78 of file GameManager.cpp.
References m_fDeltaTime, m_lObjects, and m_pGameApplication.
Referenced by GameApp::UpdateFrame().
bool GameManager::AddObject (GameObj3dPtr object, NiNodePtr parent)
Adds an object to the list
Parameters:
object
parent
Returns:
bool
Definition at line 99 of file GameManager.cpp.
References m_lObjects.
Referenced by Init(), and InputManager::ProcessKeyboard().
bool GameManager::AddObject (GameObj3dPtr object, NiNodePtr parent, NiPhysXScenePtr physXScene)
Adds a PhysX object to the list
Parameters:
object
parent
physXScene
Returns:
bool
Definition at line 119 of file GameManager.cpp.
References m_lObjects.
void GameManager::AddAgent (AgentPtr agent)
Adds an agent to the agent list
Parameters:
agent
Definition at line 135 of file GameManager.cpp.
References m_lAgents.
Referenced by Bee::DoExtraInits().
void GameManager::AddEnemy (GameCharacterPtr enemy)
Adds an enemy to the enemies list
Parameters:
enemy
Definition at line 145 of file GameManager.cpp.
References m_lEnemies.
Referenced by Level::AddEnemy(), and Locust::DoExtraInits().
void GameManager::RemoveEnemy (GameCharacterPtr enemy)
Removes an enemy from the enemy list
Parameters:
enemy
Definition at line 155 of file GameManager.cpp.
References m_lEnemies.
void GameManager::RemoveObject (GameObj3dPtr object)
Removes an object from the list
Parameters:
object
Definition at line 165 of file GameManager.cpp.
References m_lObjects.
QueenPtr GameManager::GetQueen () const [inline]
Definition at line 42 of file GameManager.h.
References m_spQueen.
Referenced by Bee::DoExtraInits(), InputManager::ProcessKeyboard(), InputManager::ProcessMouse(), and GameApp::UpdateFrame().
const NiTPointerList<AgentPtr>& GameManager::GetAgents () const [inline]
Definition at line 43 of file GameManager.h.
References m_lAgents.
Referenced by Separation::Execute(), Cohesion::Execute(), and Alignment::Execute().
GameApp* GameManager::GetGameApp () const [inline]
Definition at line 44 of file GameManager.h.
References m_pGameApplication.
const NiTPointerList<GameCharacterPtr>& GameManager::GetEnemies () const [inline]
Definition at line 45 of file GameManager.h.
References m_lEnemies.
Referenced by InputManager::ProcessKeyboard().
const float GameManager::GetDeltaTime () const [inline]
Definition at line 46 of file GameManager.h.
References m_fDeltaTime.
Referenced by Queen::SelectMoreSoldiers().
Member Data Documentation
friend GameManager::SingletonObj< GameManager > [private]
Definition at line 30 of file GameManager.h.
NiTPointerList<GameObj3dPtr> GameManager::m_lObjects [private]
Definition at line 52 of file GameManager.h.
Referenced by AddObject(), RemoveObject(), UpdateAll(), and ~GameManager().
NiTPointerList<AgentPtr> GameManager::m_lAgents [private]
Definition at line 53 of file GameManager.h.
Referenced by AddAgent(), GetAgents(), and ~GameManager().
NiTPointerList<GameCharacterPtr> GameManager::m_lEnemies [private]
Definition at line 54 of file GameManager.h.
Referenced by AddEnemy(), GetEnemies(), RemoveEnemy(), and ~GameManager().
QueenPtr GameManager::m_spQueen [private]
Definition at line 56 of file GameManager.h.
Referenced by GetQueen(), Init(), and ~GameManager().
GameApp* GameManager::m_pGameApplication [private]
Definition at line 57 of file GameManager.h.
Referenced by GetGameApp(), Init(), and UpdateAll().
float GameManager::m_fDeltaTime [private]
Definition at line 58 of file GameManager.h.
Referenced by GetDeltaTime(), and UpdateAll().
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/GameManager.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/GameManager.cpp