BeeSiege: FSMQueenAIControl Class Reference
FSMQueenAIControl Class Reference
#include <FSMQueenAIControl.h>
Private Member Functions
FSMQueenAIControl (Queen *queen)
void Update (int t)
void UpdatePerceptions (int t)
void Init ()
Private Attributes
GameObj * m_nearestEnemy
GameObj * m_nearestPowerUp
float m_nearestEnemyDist
float m_nearestPowerUpDist
NiPoint3 m_collidePt
bool m_willCollide
bool m_powerUpNear
float m_safetyRadius
FSMQueenMachine * m_queen_machine
Queen * m_queen
Detailed Description
Definition at line 10 of file FSMQueenAIControl.h.
Constructor & Destructor Documentation
FSMQueenAIControl::FSMQueenAIControl (Queen * queen) [private]
Definition at line 7 of file FSMQueenAIControl.cpp.
References FSMQueenMachine::AddState(), FSM_MACH_BEE, m_queen, m_queen_machine, and FSMQueenMachine::SetDefaultState().
Member Function Documentation
void FSMQueenAIControl::Update (int t) [private, virtual]
Reimplemented from FSMAIControl.
Definition at line 18 of file FSMQueenAIControl.cpp.
References m_queen, m_queen_machine, FSMQueenMachine::Reset(), FSMQueenMachine::UpdateMachine(), and UpdatePerceptions().
void FSMQueenAIControl::UpdatePerceptions (int t) [private, virtual]
Reimplemented from FSMAIControl.
Definition at line 30 of file FSMQueenAIControl.cpp.
References m_nearestEnemy, m_nearestEnemyDist, m_nearestPowerUp, m_nearestPowerUpDist, m_powerUpNear, m_safetyRadius, m_willCollide, and POWERUP_SCAN_DIST.
Referenced by Update().
void FSMQueenAIControl::Init () [private, virtual]
Reimplemented from FSMAIControl.
Member Data Documentation
GameObj* FSMQueenAIControl::m_nearestEnemy [private]
Definition at line 14 of file FSMQueenAIControl.h.
Referenced by UpdatePerceptions().
GameObj* FSMQueenAIControl::m_nearestPowerUp [private]
Definition at line 15 of file FSMQueenAIControl.h.
Referenced by UpdatePerceptions().
float FSMQueenAIControl::m_nearestEnemyDist [private]
Definition at line 16 of file FSMQueenAIControl.h.
Referenced by UpdatePerceptions().
float FSMQueenAIControl::m_nearestPowerUpDist [private]
Definition at line 17 of file FSMQueenAIControl.h.
Referenced by UpdatePerceptions().
NiPoint3 FSMQueenAIControl::m_collidePt [private]
Definition at line 18 of file FSMQueenAIControl.h.
bool FSMQueenAIControl::m_willCollide [private]
Definition at line 19 of file FSMQueenAIControl.h.
Referenced by UpdatePerceptions().
bool FSMQueenAIControl::m_powerUpNear [private]
Definition at line 20 of file FSMQueenAIControl.h.
Referenced by UpdatePerceptions().
float FSMQueenAIControl::m_safetyRadius [private]
Definition at line 21 of file FSMQueenAIControl.h.
Referenced by UpdatePerceptions().
FSMQueenMachine* FSMQueenAIControl::m_queen_machine [private]
Definition at line 28 of file FSMQueenAIControl.h.
Referenced by FSMQueenAIControl(), and Update().
Queen* FSMQueenAIControl::m_queen [private]
Definition at line 29 of file FSMQueenAIControl.h.
Referenced by FSMQueenAIControl(), and Update().
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/FSMQueenAIControl.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/FSMQueenAIControl.cpp