BeeSiege: LevelManager Class Reference
LevelManager Class Reference
#include <LevelManager.h>
Public Member Functions
bool LoadLevel (unsigned int id)
Private Member Functions
LevelManager ()
~LevelManager ()
bool ReadFloat (float &value, TiXmlElement *node, const char *child)
bool ReadEnemies (TiXmlElement *node, LevelPtr level)
Private Attributes
friend SingletonObj< LevelManager >
NiTMap< unsigned int, LevelPtr > m_lLevels
Detailed Description
Definition at line 10 of file LevelManager.h.
Constructor & Destructor Documentation
LevelManager::LevelManager () [private]
Definition at line 8 of file LevelManager.cpp.
LevelManager::~LevelManager () [private]
Definition at line 12 of file LevelManager.cpp.
References m_lLevels.
Member Function Documentation
bool LevelManager::LoadLevel (unsigned int id)
Definition at line 17 of file LevelManager.cpp.
References m_lLevels, and ReadEnemies().
bool LevelManager::ReadFloat (float & value, TiXmlElement * node, const char * child) [private]
Definition at line 47 of file LevelManager.cpp.
Referenced by ReadEnemies().
bool LevelManager::ReadEnemies (TiXmlElement * node, LevelPtr level) [private]
Definition at line 62 of file LevelManager.cpp.
References ReadFloat().
Referenced by LoadLevel().
Member Data Documentation
friend LevelManager::SingletonObj< LevelManager > [private]
Definition at line 12 of file LevelManager.h.
NiTMap<unsigned int, LevelPtr> LevelManager::m_lLevels [private]
Definition at line 22 of file LevelManager.h.
Referenced by LoadLevel(), and ~LevelManager().
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/LevelManager.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/LevelManager.cpp