BeeSiege: Locust Class Reference
Locust Class Reference
#include <Locust.h>
Public Member Functions
Locust ()
~Locust ()
Private Member Functions
void DoExtraUpdates (float fTime)
bool DoExtraInits ()
Detailed Description
Definition at line 6 of file Locust.h.
Constructor & Destructor Documentation
Locust::Locust ()
Enemy: Locust Ctor
Definition at line 21 of file Locust.cpp.
Locust::~Locust ()
Dtor
Definition at line 29 of file Locust.cpp.
Member Function Documentation
void Locust::DoExtraUpdates (float fTime) [private, virtual]
Does extra updates
Parameters:
fTime
Implements GameCharacter.
Definition at line 39 of file Locust.cpp.
References SingletonObj< GameManager >::Get(), GameCharacter::GetAgent(), GameCharacter::m_pTarget, and GameCharacter::m_spAgent.
bool Locust::DoExtraInits () [private, virtual]
Does extra initializations
Returns:
bool
Reimplemented from GameCharacter.
Definition at line 63 of file Locust.cpp.
References GameManager::AddEnemy(), GameCharacter::DoExtraInits(), SingletonObj< GameManager >::Get(), and GameCharacter::m_spAgent.
The documentation for this class was generated from the following files:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/Locust.h
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/Locust.cpp