BeeSiege: FSMEnemyMachine Class Reference
FSMEnemyMachine Class Reference
#include <FSMEnemyMachine.h>
Public Member Functions
FSMEnemyMachine (int type=FSM_MACH_ENEMY)
void UpdateMachine (int i)
void AddState (FSMState *state)
void SetDefaultState (FSMState *state)
void SetGoalID (int goal)
bool TransitionState (int goal)
void Reset ()
Detailed Description
Definition at line 8 of file FSMEnemyMachine.h.
Constructor & Destructor Documentation
FSMEnemyMachine::FSMEnemyMachine (int type = FSM_MACH_ENEMY) [inline]
Definition at line 11 of file FSMEnemyMachine.h.
References FSMMachine::m_type.
Member Function Documentation
void FSMEnemyMachine::UpdateMachine (int i) [virtual]
Reimplemented from FSMMachine.
Referenced by FSMEnemyAIControl::Update().
void FSMEnemyMachine::AddState (FSMState * state) [virtual]
Reimplemented from FSMMachine.
Referenced by FSMEnemyAIControl::FSMEnemyAIControl().
void FSMEnemyMachine::SetDefaultState (FSMState * state) [inline, virtual]
Reimplemented from FSMMachine.
Definition at line 18 of file FSMEnemyMachine.h.
References FSMMachine::m_defaultState.
Referenced by FSMEnemyAIControl::FSMEnemyAIControl().
void FSMEnemyMachine::SetGoalID (int goal) [inline, virtual]
Reimplemented from FSMMachine.
Definition at line 22 of file FSMEnemyMachine.h.
References FSMMachine::m_goalId.
bool FSMEnemyMachine::TransitionState (int goal) [virtual]
Reimplemented from FSMMachine.
void FSMEnemyMachine::Reset () [virtual]
Reimplemented from FSMMachine.
Referenced by FSMEnemyAIControl::Update().
The documentation for this class was generated from the following file:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/FSMEnemyMachine.h