BeeSiege: FSMState Class Reference
FSMState Class Reference
#include <FSMState.h>
Public Member Functions
FSMState (int type=FSM_STATE_NONE)
virtual void Enter ()
virtual void Exit ()
virtual void Update (int i)
virtual void Init ()
virtual int CheckTransitions (int t)
Public Attributes
int m_type
Detailed Description
Definition at line 9 of file FSMState.h.
Constructor & Destructor Documentation
FSMState::FSMState (int type = FSM_STATE_NONE) [inline]
Definition at line 13 of file FSMState.h.
References m_type.
Member Function Documentation
virtual void FSMState::Enter () [virtual]
Reimplemented in StateAttack, StateDead, StateFollowQueen, StateIdle, and StatePowerUp.
Referenced by FSMMachine::UpdateMachine().
virtual void FSMState::Exit () [virtual]
Reimplemented in StateAttack, StateDead, StateFollowQueen, StateIdle, and StatePowerUp.
Referenced by FSMMachine::UpdateMachine().
virtual void FSMState::Update (int i) [virtual]
Reimplemented in StateAttack, StateDead, StateFollowQueen, StateIdle, and StatePowerUp.
Referenced by FSMMachine::UpdateMachine().
virtual void FSMState::Init () [virtual]
Reimplemented in StateAttack, StateDead, StateFollowQueen, StateIdle, and StatePowerUp.
virtual int FSMState::CheckTransitions (int t) [virtual]
Reimplemented in StateAttack, StateDead, StateFollowQueen, StateIdle, and StatePowerUp.
Referenced by FSMMachine::UpdateMachine().
Member Data Documentation
int FSMState::m_type
Reimplemented in StateAttack, StateDead, StateFollowQueen, StateIdle, and StatePowerUp.
Definition at line 23 of file FSMState.h.
Referenced by FSMState(), and FSMMachine::UpdateMachine().
The documentation for this class was generated from the following file:
My Documents/Penn/CIS899/BeeSiege/Code/BeeSiege/FSMState.h